// Code generated by tool. DO NOT EDIT.
package input_options

import (
	"terraform-provider-trocco/internal/client/parameter"
)

type PagerdutyInputOptionInput struct {
	PagerdutyConnectionID  int64                                   `json:"pagerduty_connection_id"`
	Path                   string                                  `json:"path"`
	Earliest               *bool                                   `json:"parameter__earliest,omitempty"`
	Since                  *string                                 `json:"parameter__since,omitempty"`
	Until                  *string                                 `json:"parameter__until,omitempty"`
	CustomVariableSettings *[]parameter.CustomVariableSettingInput `json:"custom_variable_settings,omitempty"`
}

type UpdatePagerdutyInputOptionInput struct {
	PagerdutyConnectionID  *int64                                  `json:"pagerduty_connection_id,omitempty"`
	Path                   *string                                 `json:"path,omitempty"`
	Earliest               *bool                                   `json:"parameter__earliest,omitempty"`
	Since                  *string                                 `json:"parameter__since,omitempty"`
	Until                  *string                                 `json:"parameter__until,omitempty"`
	CustomVariableSettings *[]parameter.CustomVariableSettingInput `json:"custom_variable_settings,omitempty"`
}
