version: "2"

linters:
  enable:
    - "bodyclose"
    - "contextcheck"
    - "durationcheck"
    - "errorlint"
    - "forcetypeassert"
    - "godot"
    - "gosec"
    - "ineffassign"
    - "makezero"
    - "misspell"
    - "nilerr"
    - "predeclared"
    - "staticcheck"
    - "unconvert"
    - "unparam"
