// Code generated by tool. DO NOT EDIT.
package input_option

import (
	"terraform-provider-trocco/internal/client/entity"
)

type PagerdutyInputOptionMeta struct {
	Path     string  `json:"path"`
	Earliest *bool   `json:"parameter__earliest"`
	Since    *string `json:"parameter__since"`
	Until    *string `json:"parameter__until"`
}

type PagerdutyInputOption struct {
	PagerdutyConnectionID  int64                           `json:"pagerduty_connection_id"`
	Meta                   *PagerdutyInputOptionMeta       `json:"meta"`
	CustomVariableSettings *[]entity.CustomVariableSetting `json:"custom_variable_settings"`
}
