// Code generated by tool. DO NOT EDIT.
package input_options

import (
	"context"

	inputOptionEntities "terraform-provider-trocco/internal/client/entity/job_definition/input_option"
	inputOptionParameters "terraform-provider-trocco/internal/client/parameter/job_definition/input_option"
	"terraform-provider-trocco/internal/provider/model"
	"terraform-provider-trocco/internal/provider/model/job_definition/common"

	"github.com/hashicorp/terraform-plugin-framework/types"
)

// PagerdutyInputOption is the Terraform state model.
// tfsdk tags strip the parameter__ / path_parameter__ prefix (user-facing names).
type PagerdutyInputOption struct {
	PagerdutyConnectionID  types.Int64  `tfsdk:"pagerduty_connection_id"`
	Path                   types.String `tfsdk:"path"`
	Earliest               types.Bool   `tfsdk:"earliest"`
	Since                  types.String `tfsdk:"since"`
	Until                  types.String `tfsdk:"until"`
	CustomVariableSettings types.List   `tfsdk:"custom_variable_settings"`
}

func NewPagerdutyInputOption(
	ctx context.Context,
	e *inputOptionEntities.PagerdutyInputOption,
) *PagerdutyInputOption {
	if e == nil {
		return nil
	}

	path := types.StringValue(e.Path)

	customVariableSettings, err := common.ConvertCustomVariableSettingsToList(ctx, e.CustomVariableSettings)
	if err != nil {
		return nil
	}

	return &PagerdutyInputOption{
		PagerdutyConnectionID:  types.Int64Value(e.PagerdutyConnectionID),
		Path:                   path,
		Earliest:               types.BoolPointerValue(e.Earliest),
		Since:                  types.StringPointerValue(e.Since),
		Until:                  types.StringPointerValue(e.Until),
		CustomVariableSettings: customVariableSettings,
	}
}

// ToInput maps TF state → create parameter struct.
// The parameter struct carries correct JSON tags (with original prefix).
func (m *PagerdutyInputOption) ToInput(ctx context.Context) *inputOptionParameters.PagerdutyInputOptionInput {
	if m == nil {
		return nil
	}
	customVarSettings := common.ExtractCustomVariableSettings(ctx, m.CustomVariableSettings)
	return &inputOptionParameters.PagerdutyInputOptionInput{
		PagerdutyConnectionID:  m.PagerdutyConnectionID.ValueInt64(),
		Path:                   m.Path.ValueString(),
		Earliest:               m.Earliest.ValueBoolPointer(),
		Since:                  m.Since.ValueStringPointer(),
		Until:                  m.Until.ValueStringPointer(),
		CustomVariableSettings: model.ToCustomVariableSettingInputs(customVarSettings),
	}
}

// ToUpdateInput maps TF state → update parameter struct.
func (m *PagerdutyInputOption) ToUpdateInput(ctx context.Context) *inputOptionParameters.UpdatePagerdutyInputOptionInput {
	if m == nil {
		return nil
	}
	customVarSettings := common.ExtractCustomVariableSettings(ctx, m.CustomVariableSettings)
	return &inputOptionParameters.UpdatePagerdutyInputOptionInput{
		PagerdutyConnectionID:  m.PagerdutyConnectionID.ValueInt64Pointer(),
		Path:                   m.Path.ValueStringPointer(),
		Earliest:               m.Earliest.ValueBoolPointer(),
		Since:                  m.Since.ValueStringPointer(),
		Until:                  m.Until.ValueStringPointer(),
		CustomVariableSettings: model.ToCustomVariableSettingInputs(customVarSettings),
	}
}
