name: E2E tests

on:
  pull_request:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
      - docs/**
      - examples/**
      - templates/**
    branches:
      - main

permissions:
  contents: read

jobs:
  e2e_test:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"
          cache: false
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
      - run: go mod download
      - run: |
          make testacc
        env:
          TROCCO_API_KEY: ${{ secrets.TROCCO_API_KEY }}
          TROCCO_TEST_URL: https://trocco.io
      - run: |
          make cover-html
      - name: Archive code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: code-coverage-report
          path: tmp/cover.html
