---
name: pinact-action
on:
  pull_request: null

jobs:
  pinact:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Pin actions
        uses: suzuki-shunsuke/pinact-action@v1.0.0
        with:
          app_id: ${{ secrets.PINACT_GITHUB_APP_ID }}
          app_private_key: ${{ secrets.PINACT_GITHUB_APP_PRIVATE_KEY }}
