// Code generated by tool. DO NOT EDIT.
package job_definition

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

func PagerdutyInputOptionSchema() schema.Attribute {
	return schema.SingleNestedAttribute{
		Optional:            true,
		MarkdownDescription: "attributes of source Pagerduty",
		Attributes: map[string]schema.Attribute{
			"pagerduty_connection_id": schema.Int64Attribute{
				Required:            true,
				MarkdownDescription: "id of Pagerduty connection",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"path": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "API endpoint path",
			},
			"earliest": schema.BoolAttribute{
				Optional: true,
			},
			"since": schema.StringAttribute{
				Optional: true,
			},
			"until": schema.StringAttribute{
				Optional: true,
			},
			"custom_variable_settings": CustomVariableSettingsSchema(),
		},
	}
}
